
app:
    name :  my app

my:
   greeting :  Hello World3
   list:
     values :  one,two,three

db:
   connection :  "{url: 'http://____', userName:'foo', password:'root'}"
   host :  localhost
   port :  3306

management.endpoints.web.exposure.include: "*"

#spring.profiles.active: test

spring.application.name: spring-boot-config

spring:
  config:
    import: "optional:configserver:http://localhost:8888"


